# Setup
title:        The Experiment Factory
tagline:      ""
baseurl:      "/"
github:       "https://www.github.com/expfactory/expfactory"

# About/contact
author:
  name:       Vanessa Sochat
  url:        https://expfactory.github.io

# Version
version: 3.1.0

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

#Others
markdown: kramdown
